In [1]:
from google.colab import files
uploaded = files.upload()

Saving StudentsPerformance.csv to StudentsPerformance.csv

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv("StudentsPerformance.csv")

In [4]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [5]:
df.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [7]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [8]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [9]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [10]:
df.shape

(1000, 8)

In [11]:
score_columns=['math score','reading score','writing score']

In [12]:
score_columns

['math score', 'reading score', 'writing score']

In [13]:
df[score_columns].describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [14]:
df[score_columns].mean()

math score       66.089
reading score    69.169
writing score    68.054
dtype: float64

In [15]:
df[score_columns].median()

math score       66.0
reading score    70.0
writing score    69.0
dtype: float64

In [16]:
df[score_columns].mode()

   math score  reading score  writing score
0          65             72             74

In [17]:
df[score_columns].std()

math score       15.163080
reading score    14.600192
writing score    15.195657
dtype: float64

In [18]:
df[score_columns].quantile(0.25)

math score       57.00
reading score    59.00
writing score    57.75
Name: 0.25, dtype: float64

In [19]:
df[score_columns].quantile(0.50)

math score       66.0
reading score    70.0
writing score    69.0
Name: 0.5, dtype: float64

In [20]:
df[score_columns].quantile(0.75)

math score       77.0
reading score    79.0
writing score    79.0
Name: 0.75, dtype: float64

In [21]:
df['Total Score']=df['math score']+df['reading score']+df['writing score']

In [22]:
df['Total Score']

0      218
1      247
2      278
3      148
4      229
      ...
995    282
996    172
997    195
998    223
999    249
Name: Total Score, Length: 1000, dtype: int64

In [23]:
df['Percentage'] = (df['Total Score']/300)*100

In [24]:
df[['Total Score','Percentage']].head()

   Total Score  Percentage
0          218   72.666667
1          247   82.333333
2          278   92.666667
3          148   49.333333
4          229   76.333333

In [25]:
outlier_results = {}

for col in score_columns:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR

In [29]:
outliers = df[
    (df[col] < lower_limit) |
    (df[col] > upper_limit)
]
outlier_results[col] = outliers
print("Subject:", col)
print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Limit:", lower_limit)
print("Upper Limit:", upper_limit)
print("Number of Outliers:", len(outliers))

Subject: writing score
Q1: 57.75
Q3: 79.0
IQR: 21.25
Lower Limit: 25.875
Upper Limit: 110.875
Number of Outliers: 5

In [32]:
for subject, outliers in outlier_results.items():

    print("\nOutliers in", subject)

    if len(outliers) > 0:
        print(
            outliers[
                [
                    "gender",
                    "race/ethnicity",
                    "math score",
                    "reading score",
                    "writing score",
                    "Total Score",
                    "Percentage"
                ]
            ]
        )
    else:
        print("No outliers detected.")

Outliers in writing score
     gender race/ethnicity  math score  reading score  writing score  \
59   female        group C           0             17             10
76     male        group E          30             26             22
327    male        group A          28             23             19
596    male        group B          30             24             15
980  female        group B           8             24             23

     Total Score  Percentage
59            27    9.000000
76            78   26.000000
327           70   23.333333
596           69   23.000000
980           55   18.333333