In [1]:
from google.colab import files
uploaded=files.upload()

Saving healthcare_dataset.csv to healthcare_dataset.csv

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
df=pd.read_csv("healthcare_dataset.csv")

In [ ]:
df["Medical_Code_Category"] = df["Medical_Code"].str.replace("ICD-10-", "")

In [11]:
df.head()

,Patient_ID,Gender,Age,Medical_Condition,Admission_Date,Admission_Type,Medical_Code,Billing_Amount,Discharge_Date
0,P1001,Male,45,Hypertension,15-01-2026,Urgent,ICD-10-I10,4500.0,20-01-2026
1,P1002,Female,32,Pneumonia,16-01-2026,Emergency,ICD-10-J18,6700.5,22-01-2026
2,P1003,Male,68,Diabetes Type 2,16-01-2026,Routine,ICD-10-E11,3200.0,18-01-2026
3,P1004,Female,55,Asthma,17-01-2026,Emergency,ICD-10-J45,5800.0,19-01-2026
4,P1005,Male,29,Fracture,17-01-2026,Urgent,ICD-10-S52,8500.0,25-01-2026

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Patient_ID         500 non-null    object
 1   Gender             500 non-null    object
 2   Age                500 non-null    int64
 3   Medical_Condition  500 non-null    object
 4   Admission_Date     500 non-null    object
 5   Admission_Type     500 non-null    object
 6   Medical_Code       500 non-null    object
 7   Billing_Amount     500 non-null    float64
 8   Discharge_Date     500 non-null    object
dtypes: float64(1), int64(1), object(7)
memory usage: 35.3+ KB

In [13]:
df.describe()

              Age  Billing_Amount
count  500.000000       500.00000
mean    50.106000      7249.00100
std     15.328035      3198.96932
min     22.000000      2300.00000
25%     37.000000      4400.00000
50%     50.000000      6950.00000
75%     63.000000      9400.00000
max     78.000000     14200.00000

In [14]:
df.isnull().sum()

Patient_ID           0
Gender               0
Age                  0
Medical_Condition    0
Admission_Date       0
Admission_Type       0
Medical_Code         0
Billing_Amount       0
Discharge_Date       0
dtype: int64

In [15]:
df.dropna()

,Patient_ID,Gender,Age,Medical_Condition,Admission_Date,Admission_Type,Medical_Code,Billing_Amount,Discharge_Date
0,P1001,Male,45,Hypertension,15-01-2026,Urgent,ICD-10-I10,4500.0,20-01-2026
1,P1002,Female,32,Pneumonia,16-01-2026,Emergency,ICD-10-J18,6700.5,22-01-2026
2,P1003,Male,68,Diabetes Type 2,16-01-2026,Routine,ICD-10-E11,3200.0,18-01-2026
3,P1004,Female,55,Asthma,17-01-2026,Emergency,ICD-10-J45,5800.0,19-01-2026
4,P1005,Male,29,Fracture,17-01-2026,Urgent,ICD-10-S52,8500.0,25-01-2026
...,...,...,...,...,...,...,...,...,...
495,P1496,Female,50,COPD,20-09-2026,Emergency,ICD-10-J44,9800.0,23-09-2026
496,P1497,Male,28,Fracture,20-09-2026,Urgent,ICD-10-S52,9400.0,24-09-2026
497,P1498,Female,67,Heart Attack,21-09-2026,Emergency,ICD-10-I21,14200.0,25-09-2026
498,P1499,Male,43,Diabetes Type 2,21-09-2026,Routine,ICD-10-E11,4900.0,23-09-2026
499,P1500,Female,61,Stroke,22-09-2026,Emergency,ICD-10-I63,13900.0,26-09-2026

In [16]:
df["Admission_Date"] = pd.to_datetime(df["Admission_Date"], format="%d-%m-%Y")
df["Discharge_Date"] = pd.to_datetime(df["Discharge_Date"], format="%d-%m-%Y")
df["hospital_stay_days"] = (df["Discharge_Date"] - df["Admission_Date"]).dt.days

In [17]:
df.head()

,Patient_ID,Gender,Age,Medical_Condition,Admission_Date,Admission_Type,Medical_Code,Billing_Amount,Discharge_Date,hospital_stay_days
0,P1001,Male,45,Hypertension,2026-01-15,Urgent,ICD-10-I10,4500.0,2026-01-20,5
1,P1002,Female,32,Pneumonia,2026-01-16,Emergency,ICD-10-J18,6700.5,2026-01-22,6
2,P1003,Male,68,Diabetes Type 2,2026-01-16,Routine,ICD-10-E11,3200.0,2026-01-18,2
3,P1004,Female,55,Asthma,2026-01-17,Emergency,ICD-10-J45,5800.0,2026-01-19,2
4,P1005,Male,29,Fracture,2026-01-17,Urgent,ICD-10-S52,8500.0,2026-01-25,8

In [20]:
display(df[['Billing_Amount', 'hospital_stay_days']].describe())

       Billing_Amount  hospital_stay_days
count       500.00000           500.00000
mean       7249.00100             2.74400
std        3198.96932             1.17696
min        2300.00000             1.00000
25%        4400.00000             2.00000
50%        6950.00000             2.00000
75%        9400.00000             4.00000
max       14200.00000            10.00000